version: "3"
services:
  db:
    build: .
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: "Asia/Singapore"
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
